global:
  message: Welcome to order service prod environment
server:
  port: 8085
message: Hello from ORDER PROD
spring:
  data-source:
   url: jdbc:mysql://localhost:3306/ord_prod
   username: root
   password: root
  jpa:
    hibernate: 
      ddl-auto: update
    show-sql: true
